/* SignalBoard — minimalist frontend */

(function () {
    "use strict";

    // ── Financial term explanations ───────────────────────────
    var EXPLANATIONS = {
        // DCF Assumptions
        wacc: {
            title: "WACC",
            text: "Weighted Average Cost of Capital. The blended rate a company must earn on its assets to satisfy both debt holders and equity investors. It combines the cost of equity (what shareholders demand) and the after-tax cost of debt, weighted by the company's capital structure.",
            why: "A higher WACC means future cash flows are worth less today, lowering the intrinsic value. It is the single most sensitive input in a DCF model."
        },
        terminal_growth: {
            title: "Terminal Growth",
            text: "The perpetual growth rate applied to cash flows beyond the explicit forecast period. It represents the rate at which the company's free cash flow is assumed to grow forever.",
            why: "Even small changes (e.g. 2% vs 3%) dramatically shift the terminal value, which often comprises 50\u201375% of total enterprise value."
        },
        revenue_cagr: {
            title: "Revenue CAGR",
            text: "Compound Annual Growth Rate of revenue over the forecast period. Measures the smoothed annual rate at which top-line revenue is expected to grow.",
            why: "Revenue growth is the primary driver of future cash flows. Overly optimistic growth assumptions can inflate intrinsic value estimates."
        },
        terminal_ebitda_margin: {
            title: "Terminal EBITDA Margin",
            text: "The steady-state EBITDA margin assumed at the end of the explicit forecast period. Reflects the company\u2019s long-run operating profitability after competition and scale effects stabilize.",
            why: "Determines how much of each revenue dollar converts to operating profit in perpetuity. Margin expansion assumptions should be grounded in industry benchmarks."
        },
        // DCF Output
        pv_of_cash_flows: {
            title: "PV of Cash Flows",
            text: "The present value of all projected free cash flows during the explicit forecast period (typically 5\u201310 years), discounted back to today at the WACC.",
            why: "Represents the near-term value the company is expected to generate. A larger share vs terminal value suggests more earnings visibility."
        },
        pv_of_terminal_value: {
            title: "PV of Terminal Value",
            text: "The present value of all cash flows beyond the forecast period, captured in a single lump-sum calculation and discounted to today.",
            why: "Often the largest component of enterprise value. If it dominates (>75%), the valuation is heavily dependent on long-term assumptions."
        },
        implied_enterprise_value: {
            title: "Implied Enterprise Value",
            text: "The sum of the present value of forecast-period cash flows and the terminal value. Represents the total value of the business to all capital providers (debt + equity).",
            why: "Subtracting net debt from enterprise value yields the equity value, which divided by shares outstanding gives the implied share price."
        },
        implied_price_share: {
            title: "Implied Price / Share",
            text: "The per-share intrinsic value derived from the DCF model. Calculated as (Enterprise Value \u2013 Net Debt) \u00f7 Shares Outstanding.",
            why: "Directly comparable to the current market price. If the implied price exceeds the market price, the stock may be undervalued."
        },
        upside_downside: {
            title: "Upside / (Downside)",
            text: "The percentage difference between the DCF-implied share price and the current market price. Positive values indicate the stock trades below intrinsic value.",
            why: "Quantifies the margin of safety. A larger upside percentage suggests greater potential reward relative to the current price."
        },
        // Income Statement
        revenue: {
            title: "Revenue",
            text: "Total sales generated by the company from its core business operations before any costs are deducted. Also called top-line or net sales.",
            why: "The starting point for all profitability analysis. Consistent revenue growth signals product-market fit and pricing power."
        },
        yoy_growth: {
            title: "YoY Growth",
            text: "Year-over-year percentage change in revenue. Measures how fast the company\u2019s top line is expanding or contracting compared to the same period last year.",
            why: "Reveals whether growth is accelerating, decelerating, or turning negative\u2014critical context for forecasting future cash flows."
        },
        gross_margin: {
            title: "Gross Margin",
            text: "Revenue minus cost of goods sold, expressed as a percentage of revenue. Reflects how efficiently a company produces or delivers its products.",
            why: "Higher gross margins indicate pricing power or cost advantages. Declining margins may signal rising input costs or competitive pressure."
        },
        ebitda: {
            title: "EBITDA",
            text: "Earnings Before Interest, Taxes, Depreciation, and Amortization. A proxy for operating cash generation that strips out capital structure and non-cash charges.",
            why: "Widely used to compare operating performance across companies regardless of debt levels or accounting policies."
        },
        ebitda_margin: {
            title: "EBITDA Margin",
            text: "EBITDA divided by revenue, expressed as a percentage. Shows what share of each revenue dollar translates into operating profit before non-cash charges.",
            why: "A key measure of operating efficiency. Expanding margins suggest improving scale economics; contracting margins may indicate rising costs."
        },
        net_income: {
            title: "Net Income",
            text: "The bottom-line profit after all expenses, interest, taxes, and non-operating items are deducted from revenue. Also called net earnings or net profit.",
            why: "Drives earnings per share and ultimately shareholder returns. However, it can be distorted by one-time items and accounting choices."
        },
        diluted_eps: {
            title: "Diluted EPS",
            text: "Net income divided by the fully diluted share count (including stock options, convertible securities, and warrants). Represents earnings attributable to each share.",
            why: "The standard metric for comparing per-share profitability across companies and time periods. Forms the basis of P/E valuation."
        },
        // Balance Sheet
        cash_equivalents: {
            title: "Cash & Equivalents",
            text: "Highly liquid assets including cash on hand, money market funds, and short-term Treasury bills that can be converted to cash within 90 days.",
            why: "Indicates financial flexibility and the ability to fund operations, acquisitions, or weather downturns without raising external capital."
        },
        total_assets: {
            title: "Total Assets",
            text: "Everything the company owns: cash, receivables, inventory, property, equipment, intangibles, and investments. The sum of current and non-current assets.",
            why: "Provides context for leverage ratios and return metrics like ROA. Growth in assets should ideally be accompanied by growth in earnings."
        },
        total_debt: {
            title: "Total Debt",
            text: "The sum of short-term borrowings and long-term debt obligations. Includes bank loans, bonds, credit facilities, and capital lease obligations.",
            why: "High debt amplifies both returns and risks. Comparing debt levels to EBITDA and equity reveals whether leverage is sustainable."
        },
        total_equity: {
            title: "Total Equity",
            text: "Total assets minus total liabilities. Represents the residual claim of shareholders\u2014what would remain if the company liquidated all assets and paid all debts.",
            why: "Forms the denominator of return on equity (ROE) and the book-value anchor for value investors assessing downside protection."
        },
        book_value_share: {
            title: "Book Value / Share",
            text: "Total equity divided by shares outstanding. Represents the accounting value of each share based on the balance sheet.",
            why: "Comparing book value per share to the market price yields the price-to-book ratio, a classic value metric for capital-intensive industries."
        },
        // Capital Structure
        net_debt: {
            title: "Net Debt",
            text: "Total debt minus cash and cash equivalents. A negative value means the company has more cash than debt (net cash position).",
            why: "Net debt is subtracted from enterprise value to arrive at equity value. A net cash position provides a margin of safety in downturns."
        },
        net_debt_ebitda: {
            title: "Net Debt / EBITDA",
            text: "Measures how many years of operating earnings (EBITDA) would be needed to repay all net debt. A leverage ratio used by credit analysts.",
            why: "Below 2x is generally comfortable. Above 4x may signal overleveraging. Critical for assessing debt sustainability and credit risk."
        },
        debt_equity: {
            title: "Debt / Equity",
            text: "Total debt divided by total equity. Shows how much of the company is financed by creditors vs shareholders.",
            why: "Higher ratios mean more financial leverage\u2014amplifying gains in good times but increasing distress risk in bad times."
        },
        interest_coverage: {
            title: "Interest Coverage",
            text: "EBIT (or EBITDA) divided by interest expense. Measures how comfortably a company can service its debt payments from operating income.",
            why: "A ratio below 1.5x is a warning sign. Healthy companies typically maintain coverage above 3x to absorb earnings volatility."
        },
        current_ratio: {
            title: "Current Ratio",
            text: "Current assets divided by current liabilities. A liquidity ratio measuring the company\u2019s ability to pay short-term obligations within one year.",
            why: "Below 1.0 means the company cannot cover near-term liabilities with near-term assets\u2014a potential liquidity concern."
        },
        quick_ratio: {
            title: "Quick Ratio",
            text: "Like the current ratio but excludes inventory, which may not be easily liquidated. Also called the acid-test ratio.",
            why: "A more conservative liquidity test. Especially relevant for companies with slow-moving or perishable inventory."
        },
        // Cash Flow
        cash_from_operations: {
            title: "Cash from Operations",
            text: "Cash generated by the company\u2019s core business activities. Starts with net income and adjusts for non-cash items (depreciation, working capital changes).",
            why: "The purest measure of a company\u2019s ability to generate cash. Unlike net income, it cannot be manipulated by accounting choices."
        },
        capex: {
            title: "CapEx",
            text: "Capital Expenditures\u2014cash spent on acquiring, maintaining, or upgrading physical assets like property, plants, equipment, and technology infrastructure.",
            why: "CapEx is subtracted from operating cash flow to derive free cash flow. High CapEx intensity reduces cash available for shareholders."
        },
        free_cash_flow: {
            title: "Free Cash Flow",
            text: "Cash from operations minus capital expenditures. The cash available to pay dividends, repurchase shares, reduce debt, or fund acquisitions.",
            why: "The foundation of DCF valuation. Companies that consistently generate positive FCF have the financial flexibility to create shareholder value."
        },
        fcf_margin: {
            title: "FCF Margin",
            text: "Free cash flow as a percentage of revenue. Shows how efficiently the company converts sales into actual spendable cash.",
            why: "A high FCF margin indicates a capital-light business model with strong cash conversion\u2014a hallmark of quality compounders."
        },
        fcf_yield: {
            title: "FCF Yield",
            text: "Free cash flow divided by market capitalization (or enterprise value). The cash return you would earn if you bought the entire company at its current price.",
            why: "An FCF yield above 5\u20137% may signal undervaluation. It is the cash-based equivalent of an earnings yield."
        },
        fcf_share: {
            title: "FCF / Share",
            text: "Free cash flow divided by diluted shares outstanding. The per-share cash generation of the business.",
            why: "Allows direct comparison to dividends per share and EPS, revealing whether the company generates enough cash to support its payout."
        },
        // Profitability
        roe: {
            title: "ROE",
            text: "Return on Equity. Net income divided by average shareholders\u2019 equity. Measures how effectively management uses equity capital to generate profits.",
            why: "A consistently high ROE (>15%) suggests a durable competitive advantage. But beware of companies boosting ROE through excessive leverage."
        },
        roa: {
            title: "ROA",
            text: "Return on Assets. Net income divided by average total assets. Shows how efficiently a company uses all of its assets to produce earnings.",
            why: "Unlike ROE, ROA is not inflated by leverage. A useful cross-industry profitability benchmark."
        },
        roic: {
            title: "ROIC",
            text: "Return on Invested Capital. After-tax operating profit divided by total invested capital (equity + net debt). Measures value creation per dollar of capital deployed.",
            why: "The gold standard of profitability metrics. ROIC consistently above WACC means the company is creating economic value."
        },
        asset_turnover: {
            title: "Asset Turnover",
            text: "Revenue divided by average total assets. Measures how efficiently a company uses its asset base to generate sales.",
            why: "A component of the DuPont decomposition of ROE. Higher turnover means the company wrings more revenue from each dollar of assets."
        },
        inventory_turnover: {
            title: "Inventory Turnover",
            text: "Cost of goods sold divided by average inventory. Indicates how many times inventory is sold and replaced during the year.",
            why: "Higher turnover means less capital tied up in inventory. Low turnover may signal overstocking or obsolescence risk."
        },
        dso: {
            title: "DSO",
            text: "Days Sales Outstanding. Average accounts receivable divided by daily revenue. Measures how quickly customers pay their invoices.",
            why: "Rising DSO can indicate deteriorating collection practices or customer credit quality. Lower is generally better."
        },
        dpo: {
            title: "DPO",
            text: "Days Payable Outstanding. Average accounts payable divided by daily cost of goods sold. Measures how long the company takes to pay its suppliers.",
            why: "Higher DPO means the company retains cash longer, but excessively stretching payables can damage supplier relationships."
        },
        cash_conversion_cycle: {
            title: "Cash Conversion Cycle",
            text: "DSO + Days Inventory Outstanding \u2013 DPO. Measures the number of days between paying for raw materials and collecting cash from customers.",
            why: "A shorter cycle means faster cash generation. Negative cycles (like Amazon) indicate the company collects before it pays\u2014a powerful advantage."
        },
        // Market Snapshot
        market_cap: {
            title: "Market Cap",
            text: "Share price multiplied by total shares outstanding. The total market value of a company\u2019s equity as determined by investors in the public market.",
            why: "Defines size classification (small/mid/large cap) and liquidity. Larger companies tend to have lower volatility and tighter bid-ask spreads."
        },
        enterprise_value: {
            title: "Enterprise Value",
            text: "Market cap plus net debt (total debt minus cash). Represents the total cost to acquire the entire business, including assuming its debts.",
            why: "The correct denominator for valuation multiples like EV/EBITDA, because it captures the value to all capital providers, not just equity holders."
        },
        shares_outstanding: {
            title: "Shares Outstanding",
            text: "The total number of shares currently held by all shareholders, including restricted shares held by insiders and institutions.",
            why: "The divisor used to compute per-share metrics (EPS, book value, FCF per share). Dilution from stock issuance erodes per-share value."
        },
        "52_week_range": {
            title: "52-Week Range",
            text: "The lowest and highest prices at which the stock has traded over the past 52 weeks. Provides context for the current price\u2019s position within its recent trading history.",
            why: "Stocks near the bottom of their range may be undervalued or in distress. Stocks near the top may signal momentum or overvaluation."
        },
        avg_volume_3m: {
            title: "Avg Volume (3M)",
            text: "The average number of shares traded daily over the past three months. A proxy for how easily shares can be bought or sold without moving the price.",
            why: "Low volume stocks are harder to enter and exit, and may have wider bid-ask spreads\u2014important for position sizing."
        },
        dividend_yield: {
            title: "Dividend Yield",
            text: "Annual dividends per share divided by the current share price, expressed as a percentage. The cash income return from holding the stock.",
            why: "A component of total return alongside capital gains. Very high yields may signal a pending dividend cut rather than generosity."
        },
        beta: {
            title: "Beta",
            text: "A measure of the stock\u2019s volatility relative to the overall market (typically the S&P 500). A beta of 1.0 means the stock moves in line with the market.",
            why: "Used to estimate the cost of equity via CAPM. Higher beta stocks require a higher return to compensate investors for greater systematic risk."
        },
        short_interest: {
            title: "Short Interest",
            text: "The percentage of shares outstanding that have been sold short and not yet covered. Represents bearish bets against the stock.",
            why: "Elevated short interest (>10%) may indicate negative sentiment, but it can also fuel short squeezes if the stock rises."
        },
        rsi_14: {
            title: "RSI(14)",
            text: "Relative Strength Index over 14 periods. A momentum oscillator measuring the speed and magnitude of recent price changes on a 0\u2013100 scale.",
            why: "Above 70 signals overbought conditions (potential pullback). Below 30 signals oversold (potential bounce). For long-term value investors, an oversold RSI on a fundamentally sound stock can be an attractive entry point."
        },
        // Capital Efficiency
        r_d_intensity: {
            title: "R&D Intensity",
            text: "Research & Development expenditure as a percentage of revenue. Measures how much of each revenue dollar is reinvested into innovation and product development.",
            why: "High R&D intensity (>10%) is typical for tech and pharma. It suggests a commitment to future growth, but must be evaluated against actual revenue growth to assess ROI."
        },
        capex_intensity: {
            title: "CapEx Intensity",
            text: "Capital Expenditures as a percentage of revenue. Measures how much of each revenue dollar is spent on maintaining and expanding physical assets.",
            why: "Capital-light businesses (low CapEx intensity) generate more free cash flow per dollar of revenue. High CapEx intensity is typical for utilities and energy."
        },
        r_d_capex: {
            title: "R&D / CapEx",
            text: "The ratio of R&D spending to Capital Expenditures. Indicates whether the company invests more in innovation (R&D) or physical assets (CapEx).",
            why: "A ratio above 2x suggests an innovation-driven business model. Below 0.5x indicates asset-heavy operations. Useful for comparing capital allocation strategies."
        },
        r_d_roi_proxy: {
            title: "R&D ROI Proxy",
            text: "Revenue growth rate divided by R&D intensity. A rough measure of how much growth each point of R&D spending generates.",
            why: "Higher values suggest efficient R&D spending that translates into revenue growth. Negative or very low values may indicate R&D that is not yielding commercial results."
        },
        // Price Target
        dcf: {
            title: "DCF Weight",
            text: "The weighting assigned to the discounted cash flow model in the blended price target. Reflects how much the intrinsic value estimate contributes to the final target.",
            why: "A higher DCF weight signals greater reliance on fundamental valuation. Typically receives the largest weight in value-oriented analysis."
        },
        comps: {
            title: "Comps Weight",
            text: "The weighting assigned to comparable company analysis (relative valuation using multiples like EV/EBITDA or P/E from peer companies).",
            why: "Comps provide a market-based sanity check on the DCF. Useful when the company has close public peers with similar growth profiles."
        },
        technical: {
            title: "Technical Weight",
            text: "The weighting assigned to technical analysis signals (price trends, support/resistance levels, momentum indicators).",
            why: "Typically receives a small weight in fundamental analysis. Captures near-term price dynamics that DCF and comps may not reflect."
        },
        // Risk
        severity: {
            title: "Severity",
            text: "The potential magnitude of impact if the risk factor materializes. Rated as Low, Medium, or High based on the possible effect on earnings, cash flow, or business continuity.",
            why: "Helps prioritize which risks to monitor most closely. High-severity risks warrant deeper analysis and potentially a wider margin of safety."
        },
        probability: {
            title: "Probability",
            text: "The estimated likelihood that the risk factor will actually occur. Rated as Low, Medium, or High based on historical precedent and current conditions.",
            why: "Combined with severity, it helps assess expected impact. A high-probability, high-severity risk is a red flag for the investment thesis."
        }
    };

    var page = document.body.dataset.page;

    if (page === "list") initListPage();
    else if (page === "detail") initDetailPage();

    // ── List Page ────────────────────────────────────────────

    function initListPage() {
        var container = document.getElementById("ticker-container");

        fetchScreenedStocks();

        async function fetchScreenedStocks() {
            try {
                var res = await fetch("/screened");
                var data = await res.json();
                var stocks = data.stocks || [];
                if (stocks.length > 0) {
                    renderStocks(stocks);
                } else {
                    fetchSignals();
                }
            } catch (err) {
                fetchSignals();
            }
        }

        async function fetchSignals() {
            try {
                var res = await fetch("/signals");
                var data = await res.json();
                var signals = data.signals || [];
                var top3 = signals.slice(0, 3);
                renderLegacyTickers(top3);
            } catch (err) {
                container.innerHTML =
                    '<div class="empty-state">' +
                    '<div class="icon">&#9888;</div>' +
                    '<div class="title">Connection Error</div>' +
                    '<div class="subtitle">Could not reach the SignalBoard API.</div>' +
                    "</div>";
            }
        }

        function renderStocks(stocks) {
            if (stocks.length === 0) {
                container.innerHTML =
                    '<div class="empty-state">' +
                    '<div class="icon">&#8212;</div>' +
                    '<div class="title">No Stocks Screened</div>' +
                    '<div class="subtitle">The screener has not run yet.</div>' +
                    "</div>";
                return;
            }

            var html = '<hr class="rule">';
            for (var i = 0; i < stocks.length; i++) {
                html += renderStockRow(stocks[i], i);
                html += '<hr class="rule">';
            }

            // Pick generation date
            if (stocks.length > 0 && stocks[0].generated_at) {
                var d = new Date(stocks[0].generated_at);
                var months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
                var dateStr = months[d.getMonth()] + " " + d.getDate() + ", " + d.getFullYear();
                html += '<div class="pick-date">Picks generated ' + dateStr + '</div>';
            }
            container.innerHTML = html;
        }

        function renderStockRow(s, index) {
            var upside = s.dcf_upside_pct != null ? (s.dcf_upside_pct * 100).toFixed(0) : "\u2014";
            var mos = s.margin_of_safety != null ? (s.margin_of_safety * 100).toFixed(0) : "\u2014";
            var iv = s.intrinsic_value != null ? "$" + Number(s.intrinsic_value).toFixed(2) : "\u2014";
            var price = s.current_price != null ? "$" + Number(s.current_price).toFixed(2) : "\u2014";
            var fcfYield = s.fcf_yield != null ? (s.fcf_yield * 100).toFixed(1) + "%" : "\u2014";
            var rank = s.rank || (index + 1);

            var html = '<a class="ticker-row" href="/detail.html?ticker=' + encodeURIComponent(s.ticker) + '&source=screened">';

            // Primary line: rank + ticker + name + DCF upside
            html += '<div class="row-main">';
            html += '<span class="rank">#' + rank + '</span>';
            html += '<div class="row-info">';
            html += '<span class="symbol">' + escapeHtml(s.ticker) + '</span>';
            html += '<span class="name-label">' + escapeHtml(s.short_name || "") + '</span>';
            html += '</div>';
            var upsideSign = s.dcf_upside_pct != null && s.dcf_upside_pct >= 0 ? "+" : "";
            html += '<span class="dcf-upside">' + upsideSign + upside + '%</span>';
            html += '</div>';

            // Margin of safety gauge (thin bar)
            var mosPct = s.margin_of_safety != null ? Math.min(Math.round(s.margin_of_safety * 100), 100) : 0;
            html += '<div class="mos-gauge">';
            html += '<div class="mos-fill" style="width:' + mosPct + '%"></div>';
            html += '</div>';

            // Metrics line
            html += '<div class="row-metrics">';
            html += '<span class="metric">IV ' + iv + '</span>';
            html += '<span class="metric">Price ' + price + '</span>';
            html += '<span class="metric">MoS ' + mos + '%</span>';
            html += '<span class="metric">FCF Yld ' + fcfYield + '</span>';
            html += '</div>';

            // Context line: sector + market cap
            html += '<div class="row-context">';
            html += '<span class="context-label">' + escapeHtml(s.sector || "") + '</span>';
            if (s.market_cap) {
                html += '<span class="context-label">' + formatMarketCap(s.market_cap) + '</span>';
            }
            html += '</div>';

            html += '</a>';
            return html;
        }

        function renderLegacyTickers(signals) {
            if (signals.length === 0) {
                container.innerHTML =
                    '<div class="empty-state">' +
                    '<div class="icon">&#8212;</div>' +
                    '<div class="title">No Signals</div>' +
                    '<div class="subtitle">The algorithm has not generated signals yet.</div>' +
                    "</div>";
                return;
            }

            var html = '<hr class="rule">';
            for (var i = 0; i < signals.length; i++) {
                html += '<a class="ticker-row" href="/detail.html?ticker=' + encodeURIComponent(signals[i].ticker) + '">';
                html += '<div class="row-main">';
                html += '<div class="row-info">';
                html += '<span class="symbol">' + escapeHtml(signals[i].ticker) + '</span>';
                html += '</div>';
                html += '</div>';
                html += '<span class="context-label">' + escapeHtml(signals[i].sector || "") + '</span>';
                html += '</a><hr class="rule">';
            }
            container.innerHTML = html;
        }
    }

    // ── Detail Page ──────────────────────────────────────────

    function initDetailPage() {
        var contentEl = document.getElementById("detail-content");
        var titleEl = document.getElementById("detail-title");
        var backBtn = document.getElementById("back-btn");

        backBtn.addEventListener("click", function (e) {
            e.preventDefault();
            if (window.history.length > 1) {
                window.history.back();
            } else {
                window.location.href = "/";
            }
        });

        var params = new URLSearchParams(window.location.search);
        var ticker = params.get("ticker");
        var source = params.get("source");

        if (!ticker) {
            contentEl.innerHTML =
                '<div class="empty-state"><div class="icon">&#10067;</div>' +
                '<div class="title">No Ticker</div>' +
                '<div class="subtitle">No ticker specified in the URL.</div></div>';
            return;
        }

        titleEl.textContent = ticker.toUpperCase();

        fetchReport(ticker);

        async function fetchReport(ticker) {
            contentEl.innerHTML = '<div class="loading"></div>';
            try {
                var res = await fetch("/report/" + encodeURIComponent(ticker));
                if (!res.ok) throw new Error("Not found");
                var data = await res.json();
                contentEl.innerHTML = renderReport(data);
                // Section summary toggle on header click
                contentEl.addEventListener('click', function(e) {
                    var header = e.target.closest('.report-section-header[data-summary]');
                    if (!header) return;
                    var id = header.getAttribute('data-summary');
                    var panel = document.getElementById('summary-' + id);
                    if (!panel) return;
                    panel.classList.toggle('open');
                    header.classList.toggle('summary-active');
                });
                // Explanation panel click handler
                initExplainPanel(contentEl);
                var tocEl = document.getElementById("report-toc");
                if (tocEl) renderTOC(tocEl);
            } catch (err) {
                console.error("Report render failed:", err);
                if (source === "screened") {
                    fetchScreenedDetail(ticker);
                } else {
                    fetchLegacyDetail(ticker);
                }
            }
        }

        // ── Report rendering ─────────────────────────────────────

        function renderReport(data) {
            var sections = [
                { id: "thesis", title: "Investment Thesis", html: renderThesis(data.thesis) },
                { id: "dcf", title: "DCF Valuation", html: renderDCF(data.dcf) },
                { id: "snapshot", title: "Market Snapshot", html: renderSnapshot(data.snapshot) },
                { id: "cashflow", title: "Cash Flow Statement", html: renderCashFlow(data.cash_flow) },
                { id: "income", title: "Income Statement", html: renderIncomeStatement(data.income_statement) },
                { id: "balance", title: "Balance Sheet", html: renderBalanceSheet(data.balance_sheet) },
                { id: "capital", title: "Capital Structure", html: renderCapitalStructure(data.capital_structure) },
                { id: "profitability", title: "Profitability & Efficiency", html: renderProfitability(data.profitability) },
                { id: "capeff", title: "Capital Efficiency", html: renderCapitalEfficiency(data.capital_efficiency) },
                { id: "risks", title: "Risk Factors", html: renderRisks(data.risks) },
                { id: "pricetarget", title: "Price Target Derivation", html: renderPriceTarget(data.price_target) },
                { id: "verdict", title: "Verdict", html: renderVerdict(data.verdict, data.header) }
            ];

            var html = renderReportHeader(data.header);
            html += '<div class="report-disclaimer" style="font-size:0.6rem;color:#999;text-align:center;padding:8px 0;letter-spacing:0.08em;text-transform:uppercase">Generated by SignalBoard Analytics Engine \u00b7 For Research Purposes Only</div>';
            var summaries = data.section_summaries || {};
            var sectionIndex = 0;
            for (var i = 0; i < sections.length; i++) {
                var s = sections[i];
                if (!s.html) continue;
                html += wrapSection(s.id, s.title, s.html, sectionIndex, summaries[s.id] || '');
                sectionIndex++;
            }

            // Store sections for TOC building
            window._reportSections = sections.filter(function (s) { return !!s.html; });

            return html;
        }

        function wrapSection(id, title, content, index, summary) {
            var num = String(index).padStart(2, '0');
            var summaryHtml = summary
                ? '<div class="section-summary" id="summary-' + id + '">' +
                  '<div class="section-summary-inner">' +
                  '<span class="summary-label">Key Takeaway</span>' +
                  escapeHtml(summary) +
                  '</div></div>'
                : '';
            return (
                '<section class="report-section" id="section-' + id + '">' +
                '<div class="report-section-header" data-summary="' + id + '">' +
                '<span class="section-num">' + num + '</span> ' + escapeHtml(title) +
                '</div>' +
                summaryHtml +
                '<div class="report-section-body">' +
                content +
                '</div></section>'
            );
        }

        function renderTOC(tocEl) {
            var sections = window._reportSections || [];
            var html = '<ul>';
            for (var i = 0; i < sections.length; i++) {
                var s = sections[i];
                html += '<li><a href="#section-' + s.id + '" id="toc-' + s.id + '" data-section="' + s.id + '">' + escapeHtml(s.title) + '</a></li>';
            }
            html += '</ul>';
            tocEl.innerHTML = html;
            setupScrollTracking();
        }

        function setupScrollTracking() {
            var sectionEls = document.querySelectorAll('.report-section');
            if (!sectionEls.length) return;

            var observer = new IntersectionObserver(function (entries) {
                entries.forEach(function (entry) {
                    if (entry.isIntersecting) {
                        var links = document.querySelectorAll('.report-toc a');
                        for (var i = 0; i < links.length; i++) {
                            links[i].classList.remove('active');
                        }
                        var id = entry.target.id.replace('section-', '');
                        var activeLink = document.getElementById('toc-' + id);
                        if (activeLink) {
                            activeLink.classList.add('active');
                            activeLink.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'center' });
                        }
                    }
                });
            }, {
                rootMargin: '-80px 0px -70% 0px',
                threshold: 0
            });

            for (var i = 0; i < sectionEls.length; i++) {
                observer.observe(sectionEls[i]);
            }

            var tocLinks = document.querySelectorAll('.report-toc a');
            for (var j = 0; j < tocLinks.length; j++) {
                tocLinks[j].addEventListener('click', function (e) {
                    e.preventDefault();
                    var targetId = 'section-' + this.getAttribute('data-section');
                    var target = document.getElementById(targetId);
                    if (target) {
                        target.scrollIntoView({ behavior: 'smooth', block: 'start' });
                    }
                });
            }
        }

        function renderReportHeader(h) {
            if (!h) return "";
            var ratingClass = (h.rating || "").toLowerCase().replace(/\s+/g, "-");
            var gaugeMap = {"strong-sell": 10, "sell": 25, "hold": 50, "buy": 75, "strong-buy": 90};
            var gaugePos = gaugeMap[ratingClass] || 50;
            var upsideClass = (h.upside_pct || 0) >= 0 ? "positive" : "negative";

            var html = '<div class="report-header">';
            html += '<div class="report-header-top">';
            html += '<div class="report-header-info">';
            html += '<h1>' + escapeHtml(h.name || h.ticker) + '</h1>';
            html += '<div class="header-meta">' + escapeHtml(h.ticker) + ' \u00b7 ' + escapeHtml(h.sector || '') + ' \u00b7 ' + escapeHtml(h.exchange || '') + '</div>';
            html += '</div>';
            html += '<div class="header-price"><span class="pt-value">' + fmtUSD(h.current_price) + '</span></div>';
            html += '</div>';

            // Confidence gauge
            html += '<div class="confidence-gauge">';
            html += '<div class="gauge-track">';
            html += '<div class="gauge-fill ' + ratingClass + '" style="width:' + gaugePos + '%"></div>';
            html += '<div class="gauge-indicator ' + ratingClass + '" style="left:' + gaugePos + '%;background:' + (gaugePos > 50 ? '#2d6a4f' : gaugePos < 50 ? '#c1292e' : '#adb5bd') + '"></div>';
            html += '</div>';
            html += '<div class="gauge-labels">';
            html += '<span class="gauge-label' + (ratingClass === "strong-sell" ? " active" : "") + '">Strong Sell</span>';
            html += '<span class="gauge-label' + (ratingClass === "sell" ? " active" : "") + '">Sell</span>';
            html += '<span class="gauge-label' + (ratingClass === "hold" ? " active" : "") + '">Hold</span>';
            html += '<span class="gauge-label' + (ratingClass === "buy" ? " active" : "") + '">Buy</span>';
            html += '<span class="gauge-label' + (ratingClass === "strong-buy" ? " active" : "") + '">Strong Buy</span>';
            html += '</div>';
            html += '</div>';

            // Key metrics row
            html += '<div class="price-target-row">';
            html += '<div class="pt-item"><span class="pt-label">Target</span><span class="pt-value">' + fmtUSD(h.price_target) + '</span></div>';
            html += '<div class="pt-item"><span class="pt-label">Upside</span><span class="pt-value ' + upsideClass + '">' + fmtPctSigned(h.upside_pct) + '</span></div>';
            html += '<div class="pt-item"><span class="pt-label">Date</span><span class="pt-value" style="font-size:0.8rem">' + escapeHtml(h.date || '') + '</span></div>';
            html += '</div>';
            html += '</div>';
            return html;
        }

        function renderThesis(t) {
            if (!t || !t.text) return "";
            return '<div class="thesis-section"><span class="thesis-label">Core Thesis</span><p class="thesis-text">' + escapeHtml(t.text) + '</p></div>';
        }

        function renderSnapshot(s) {
            if (!s) return "";
            var items = [
                { label: "Market Cap", value: fmtB(s.market_cap) },
                { label: "Enterprise Value", value: fmtB(s.enterprise_value) },
                { label: "Shares Outstanding", value: fmtNum(s.shares_outstanding) },
                { label: "52-Week Range", value: fmtUSD(s.range_52w_low) + " \u2013 " + fmtUSD(s.range_52w_high) },
                { label: "Avg Volume (3M)", value: fmtNum(s.avg_volume_3m) },
                { label: "Dividend Yield", value: fmtPctReport(s.dividend_yield) },
                { label: "Beta", value: fmtX(s.beta) },
                { label: "Short Interest", value: fmtPctReport(s.short_interest_pct) }
            ];
            var html = '<div class="snapshot-grid">';
            for (var i = 0; i < items.length; i++) {
                var ek = items[i].label.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");
                var he = ek && typeof EXPLANATIONS !== "undefined" && EXPLANATIONS[ek];
                html += '<div class="snapshot-item"><span class="snapshot-label' + (he ? ' explainable' : '') + '"' + (he ? ' data-explain="' + ek + '"' : '') + '>' + items[i].label + '</span><span class="snapshot-value">' + items[i].value + '</span></div>';
            }
            html += '</div>';

            // RSI(14) gauge
            if (s.rsi_14 != null) {
                var rsiVal = s.rsi_14;
                var rsiPct = Math.max(0, Math.min(100, rsiVal));
                var rsiStatus = rsiVal < 30 ? "Oversold" : rsiVal > 70 ? "Overbought" : "Neutral";
                var rsiStatusClass = rsiVal < 30 ? "oversold" : rsiVal > 70 ? "overbought" : "neutral";
                html += '<div class="rsi-gauge">';
                html += '<div class="rsi-header">';
                html += '<span class="rsi-title explainable" data-explain="rsi_14">RSI(14)</span>';
                html += '<span class="rsi-value">' + rsiVal.toFixed(1) + '</span>';
                html += '<span class="rsi-status ' + rsiStatusClass + '">' + rsiStatus + '</span>';
                html += '</div>';
                html += '<div class="rsi-track">';
                html += '<div class="rsi-zone rsi-oversold" style="width:30%"></div>';
                html += '<div class="rsi-zone rsi-neutral" style="width:40%"></div>';
                html += '<div class="rsi-zone rsi-overbought" style="width:30%"></div>';
                html += '<div class="rsi-indicator" style="left:' + rsiPct + '%"></div>';
                html += '</div>';
                html += '<div class="rsi-labels">';
                html += '<span>0</span><span>30</span><span>70</span><span>100</span>';
                html += '</div>';
                html += '</div>';
            }

            return html;
        }

        function renderFinTable(title, sectionId, headers, rows, options) {
            options = options || {};
            var html = '<div class="fin-table-wrapper">';
            if (title) html += '<h4>' + escapeHtml(title) + '</h4>';
            html += '<table class="fin-table">';
            html += '<thead><tr><th></th>';
            for (var h = 0; h < headers.length; h++) {
                html += '<th>' + escapeHtml(String(headers[h])) + '</th>';
            }
            html += '</tr></thead><tbody>';
            for (var r = 0; r < rows.length; r++) {
                var row = rows[r];
                var cls = "";
                if (row.type === "header") cls = "row-header";
                else if (row.type === "subtotal") cls = "row-subtotal";
                else if (row.type === "pct") cls = "row-pct";
                var explainKey = (row.label || "").toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");
                var hasExplain = explainKey && typeof EXPLANATIONS !== "undefined" && EXPLANATIONS[explainKey];
                html += '<tr class="' + cls + '"><td' + (hasExplain ? ' class="explainable" data-explain="' + explainKey + '"' : '') + '>' + escapeHtml(row.label) + '</td>';
                var vals = row.values || [];
                for (var v = 0; v < headers.length; v++) {
                    html += '<td>' + (v < vals.length ? formatCellValue(vals[v], row.format) : "\u2014") + '</td>';
                }
                html += '</tr>';
            }
            html += '</tbody></table></div>';
            return html;
        }

        function formatCellValue(val, format) {
            if (val == null) return "\u2014";
            if (format === "pct") return fmtPctReport(val);
            if (format === "usd") return fmtUSD(val);
            if (format === "millions") return fmtM(val);
            if (format === "billions") return fmtB(val);
            if (format === "x") return fmtX(val);
            if (typeof val === "number") {
                if (Math.abs(val) >= 1e9) return fmtB(val);
                if (Math.abs(val) >= 1e6) return fmtM(val);
                return fmtNum(val);
            }
            return escapeHtml(String(val));
        }

        function renderIncomeStatement(data) {
            if (!data || data.length === 0) return "";
            var headers = data.map(function (d) { return d.year; });
            var rows = [
                { label: "Revenue", values: data.map(function (d) { return d.revenue; }), type: "header", format: "millions" },
                { label: "YoY Growth", values: data.map(function (d) { return d.yoy_growth; }), type: "pct", format: "pct" },
                { label: "Gross Margin", values: data.map(function (d) { return d.gross_margin; }), type: "pct", format: "pct" },
                { label: "EBITDA", values: data.map(function (d) { return d.ebitda; }), format: "millions" },
                { label: "EBITDA Margin", values: data.map(function (d) { return d.ebitda_margin; }), type: "pct", format: "pct" },
                { label: "Net Income", values: data.map(function (d) { return d.net_income; }), type: "subtotal", format: "millions" },
                { label: "Diluted EPS", values: data.map(function (d) { return d.diluted_eps; }), format: "usd" }
            ];
            return renderFinTable(null, "income", headers, rows);
        }

        function renderBalanceSheet(data) {
            if (!data || data.length === 0) return "";
            var headers = data.map(function (d) { return d.year; });
            var rows = [
                { label: "Cash & Equivalents", values: data.map(function (d) { return d.cash; }), format: "millions" },
                { label: "Total Assets", values: data.map(function (d) { return d.total_assets; }), type: "header", format: "millions" },
                { label: "Total Debt", values: data.map(function (d) { return (d.long_term_debt || 0) + (d.short_term_debt || 0); }), format: "millions" },
                { label: "Total Equity", values: data.map(function (d) { return d.total_equity; }), type: "subtotal", format: "millions" },
                { label: "Book Value / Share", values: data.map(function (d) { return d.book_value_per_share; }), format: "usd" }
            ];
            return renderFinTable(null, "balance", headers, rows);
        }

        function renderCapitalStructure(data) {
            if (!data) return "";
            var rows = [
                { label: "Net Debt", values: [data.net_debt], format: "millions" },
                { label: "Net Debt / EBITDA", values: [data.net_debt_ebitda], format: "x" },
                { label: "Debt / Equity", values: [data.debt_to_equity], format: "x" },
                { label: "Interest Coverage", values: [data.interest_coverage], format: "x" },
                { label: "Current Ratio", values: [data.current_ratio], format: "x" },
                { label: "Quick Ratio", values: [data.quick_ratio], format: "x" }
            ];
            return renderFinTable(null, "capital", ["Current"], rows);
        }

        function renderCashFlow(data) {
            if (!data || data.length === 0) return "";
            var headers = data.map(function (d) { return d.year; });
            var rows = [
                { label: "Cash from Operations", values: data.map(function (d) { return d.cfo; }), type: "header", format: "millions" },
                { label: "CapEx", values: data.map(function (d) { return d.capex; }), format: "millions" },
                { label: "Free Cash Flow", values: data.map(function (d) { return d.fcf; }), type: "subtotal", format: "millions" },
                { label: "FCF Margin", values: data.map(function (d) { return d.fcf_margin; }), type: "pct", format: "pct" },
                { label: "FCF Yield", values: data.map(function (d) { return d.fcf_yield; }), type: "pct", format: "pct" },
                { label: "FCF / Share", values: data.map(function (d) { return d.fcf_per_share; }), format: "usd" }
            ];
            return renderFinTable(null, "cashflow", headers, rows);
        }

        function renderDCF(dcf) {
            if (!dcf) return "";
            var html = "";

            if (dcf.assumptions) {
                var a = dcf.assumptions;
                var aRows = [
                    { label: "WACC", values: [a.wacc], format: "pct" },
                    { label: "Terminal Growth", values: [a.terminal_growth], format: "pct" },
                    { label: "Revenue CAGR", values: [a.revenue_cagr], format: "pct" },
                    { label: "Terminal EBITDA Margin", values: [a.terminal_ebitda_margin], format: "pct" }
                ];
                html += '<div class="dcf-sub-table">';
                html += renderFinTable("Assumptions", "dcf-assumptions", ["Value"], aRows);
                html += '</div>';
            }

            if (dcf.output) {
                var o = dcf.output;
                var oRows = [
                    { label: "PV of Cash Flows", values: [o.pv_fcfs], format: "millions" },
                    { label: "PV of Terminal Value", values: [o.pv_terminal], format: "millions" },
                    { label: "Implied Enterprise Value", values: [o.implied_ev], type: "subtotal", format: "millions" },
                    { label: "Implied Price / Share", values: [o.implied_price], type: "header", format: "usd" },
                    { label: "Upside / (Downside)", values: [o.upside_pct != null ? fmtPctSigned(o.upside_pct) : null], type: "pct" }
                ];
                html += '<div class="dcf-sub-table">';
                html += renderFinTable("Valuation Output", "dcf-output", ["Value"], oRows);
                html += '</div>';
            }

            if (dcf.sensitivity) {
                html += '<div class="sensitivity-wrapper">';
                html += renderSensitivityMatrix(dcf.sensitivity, dcf.output ? dcf.output.current_price : null);
                html += '</div>';
            }

            return html;
        }

        function renderSensitivityMatrix(sens, currentPrice) {
            if (!sens || !sens.matrix) return "";
            var waccVals = sens.wacc_values || [];
            var growthVals = sens.growth_values || [];
            var matrix = sens.matrix || [];
            var midRow = Math.floor(matrix.length / 2);
            var midCol = Math.floor(waccVals.length / 2);

            var html = '<h4>Sensitivity Analysis (WACC vs Terminal Growth)</h4>';
            html += '<div class="fin-table-wrapper"><table class="fin-table sensitivity-grid">';
            html += '<thead><tr><th>WACC \\ g</th>';
            for (var g = 0; g < growthVals.length; g++) {
                html += '<th>' + fmtPctReport(growthVals[g]) + '</th>';
            }
            html += '</tr></thead><tbody>';
            for (var r = 0; r < matrix.length; r++) {
                html += '<tr><td class="row-header">' + fmtPctReport(waccVals[r]) + '</td>';
                for (var c = 0; c < matrix[r].length; c++) {
                    var val = matrix[r][c];
                    var cellClass = "";
                    if (currentPrice != null) {
                        cellClass = val > currentPrice ? "positive" : "negative";
                    }
                    if (r === midRow && c === midCol) cellClass += " base-case";
                    html += '<td class="' + cellClass.trim() + '">' + fmtUSD(val) + '</td>';
                }
                html += '</tr>';
            }
            html += '</tbody></table></div>';
            return html;
        }

        function renderProfitability(p) {
            if (!p) return "";
            var items = [
                { label: "ROE", value: fmtPctReport(p.roe) },
                { label: "ROA", value: fmtPctReport(p.roa) },
                { label: "ROIC", value: fmtPctReport(p.roic) },
                { label: "Asset Turnover", value: fmtX(p.asset_turnover) },
                { label: "Inventory Turnover", value: fmtX(p.inventory_turnover) },
                { label: "DSO", value: p.dso != null ? Math.round(p.dso) + " days" : "\u2014" },
                { label: "DPO", value: p.dpo != null ? Math.round(p.dpo) + " days" : "\u2014" },
                { label: "Cash Conversion Cycle", value: p.cash_conversion_cycle != null ? Math.round(p.cash_conversion_cycle) + " days" : "\u2014" }
            ];
            var html = '<div class="snapshot-grid">';
            for (var i = 0; i < items.length; i++) {
                var ek = items[i].label.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");
                var he = ek && typeof EXPLANATIONS !== "undefined" && EXPLANATIONS[ek];
                html += '<div class="snapshot-item"><span class="snapshot-label' + (he ? ' explainable' : '') + '"' + (he ? ' data-explain="' + ek + '"' : '') + '>' + items[i].label + '</span><span class="snapshot-value">' + items[i].value + '</span></div>';
            }
            html += '</div>';
            return html;
        }

        function renderCapitalEfficiency(ce) {
            if (!ce) return "";
            var fmtM = function(v) {
                if (v == null) return "\u2014";
                return Math.abs(v) >= 1e9 ? "$" + (v/1e9).toFixed(1) + "B" : "$" + Math.round(v/1e6) + "M";
            };
            var items = [
                { label: "R&D Intensity", value: fmtPctReport(ce.rd_intensity) },
                { label: "CapEx Intensity", value: fmtPctReport(ce.capex_intensity) },
                { label: "R&D / CapEx", value: ce.rd_to_capex != null ? ce.rd_to_capex.toFixed(1) + "x" : "\u2014" },
                { label: "R&D ROI Proxy", value: ce.rd_roi_proxy != null ? ce.rd_roi_proxy.toFixed(1) + "x" : "\u2014" },
                { label: "R&D Expense", value: fmtM(ce.rd_expense) },
                { label: "CapEx", value: fmtM(ce.capex) }
            ];
            var html = '<div class="snapshot-grid">';
            for (var i = 0; i < items.length; i++) {
                var ek = items[i].label.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");
                var he = ek && typeof EXPLANATIONS !== "undefined" && EXPLANATIONS[ek];
                html += '<div class="snapshot-item"><span class="snapshot-label' + (he ? ' explainable' : '') + '"' + (he ? ' data-explain="' + ek + '"' : '') + '>' + items[i].label + '</span><span class="snapshot-value">' + items[i].value + '</span></div>';
            }
            html += '</div>';
            return html;
        }

        function renderRisks(risks) {
            if (!risks || risks.length === 0) return "";
            var html = '<div class="fin-table-wrapper"><table class="fin-table">';
            html += '<thead><tr><th>Factor</th><th>Severity</th><th>Probability</th><th>Detail</th></tr></thead><tbody>';
            for (var i = 0; i < risks.length; i++) {
                var r = risks[i];
                var sevClass = (r.severity || "").toLowerCase();
                var probClass = (r.probability || "").toLowerCase();
                html += '<tr>';
                html += '<td>' + escapeHtml(r.factor || "") + '</td>';
                html += '<td><span class="risk-badge ' + sevClass + '">' + escapeHtml(r.severity || "") + '</span></td>';
                html += '<td><span class="risk-badge ' + probClass + '">' + escapeHtml(r.probability || "") + '</span></td>';
                html += '<td>' + escapeHtml(r.detail || "") + '</td>';
                html += '</tr>';
            }
            html += '</tbody></table></div>';
            return html;
        }

        function renderPriceTarget(pt) {
            if (!pt) return "";
            var rows = [
                { label: "DCF", weight: pt.dcf_weight, value: pt.dcf_value },
                { label: "Comps", weight: pt.comps_weight, value: pt.comps_value },
                { label: "Technical", weight: pt.technical_weight, value: pt.technical_value }
            ];

            var html = '<div class="fin-table-wrapper"><table class="fin-table">';
            html += '<thead><tr><th>Method</th><th>Weight</th><th>Value</th><th>Contribution</th></tr></thead><tbody>';
            for (var i = 0; i < rows.length; i++) {
                var r = rows[i];
                var contribution = (r.weight != null && r.value != null) ? r.weight * r.value : null;
                html += '<tr>';
                html += '<td>' + r.label + '</td>';
                html += '<td>' + fmtPctReport(r.weight) + '</td>';
                html += '<td>' + fmtUSD(r.value) + '</td>';
                html += '<td>' + fmtUSD(contribution) + '</td>';
                html += '</tr>';
            }
            html += '<tr class="row-subtotal"><td>Blended Target</td><td></td><td></td><td>' + fmtUSD(pt.blended) + '</td></tr>';
            html += '</tbody></table></div>';

            var segmentClasses = ["dcf-segment", "comps-segment", "tech-segment"];
            html += '<div class="pt-bar">';
            for (var j = 0; j < rows.length; j++) {
                var widthPct = (rows[j].weight || 0) * 100;
                if (widthPct > 0) {
                    var segCls = j < segmentClasses.length ? segmentClasses[j] : "";
                    html += '<div class="pt-bar-segment ' + segCls + '" style="width:' + widthPct + '%" title="' + rows[j].label + ': ' + fmtPctReport(rows[j].weight) + '">' + rows[j].label + '</div>';
                }
            }
            html += '</div>';

            return html;
        }

        function renderVerdict(v, header) {
            if (!v) return "";
            var ratingClass = (v.rating || "").toLowerCase().replace(/\s+/g, "-");
            var html = '<div class="verdict-box">';
            html += '<div class="verdict-rating ' + ratingClass + '">' + escapeHtml(v.rating || "") + '</div>';
            if (header && header.upside_pct != null) {
                var upsideVal = header.upside_pct;
                var upsideCls = upsideVal >= 0 ? "positive" : "negative";
                html += '<div class="verdict-upside ' + upsideCls + '" style="font-size:1.8rem;font-weight:700;margin:8px 0">' + fmtPctSigned(upsideVal) + ' upside</div>';
            }
            html += '<div class="verdict-target">Price Target: ' + fmtUSD(v.price_target) + '</div>';
            if (v.confidence != null) {
                html += '<div class="verdict-confidence">Confidence: ' + fmtPctReport(v.confidence) + '</div>';
            }
            if (v.summary) {
                html += '<p class="verdict-summary">' + escapeHtml(v.summary) + '</p>';
            }
            html += '</div>';
            return html;
        }

        // ── Report formatting helpers ────────────────────────────

        function fmtM(n) {
            if (n == null || typeof n === "string" || isNaN(n)) return typeof n === "string" ? escapeHtml(n) : "\u2014";
            return "$" + (n / 1e6).toLocaleString(undefined, { maximumFractionDigits: 1 }) + "M";
        }

        function fmtB(n) {
            if (n == null || typeof n === "string" || isNaN(n)) return typeof n === "string" ? escapeHtml(n) : "\u2014";
            if (Math.abs(n) >= 1e12) return "$" + (n / 1e12).toLocaleString(undefined, { maximumFractionDigits: 1 }) + "T";
            return "$" + (n / 1e9).toLocaleString(undefined, { maximumFractionDigits: 1 }) + "B";
        }

        function fmtPctReport(n) {
            if (n == null) return "\u2014";
            if (typeof n === "string") return escapeHtml(n);
            if (isNaN(n)) return "\u2014";
            return (n * 100).toFixed(1) + "%";
        }

        function fmtPctSigned(n) {
            if (n == null) return "\u2014";
            if (typeof n === "string") return escapeHtml(n);
            if (isNaN(n)) return "\u2014";
            return (n >= 0 ? "+" : "") + (n * 100).toFixed(1) + "%";
        }

        function fmtX(n) {
            if (n == null || typeof n === "string" || isNaN(n)) return typeof n === "string" ? escapeHtml(n) : "\u2014";
            return Number(n).toFixed(1) + "x";
        }

        function fmtUSD(n) {
            if (n == null || typeof n === "string" || isNaN(n)) return typeof n === "string" ? escapeHtml(n) : "\u2014";
            return "$" + Number(n).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
        }

        function fmtNum(n) {
            if (n == null || typeof n === "string" || isNaN(n)) return typeof n === "string" ? escapeHtml(n) : "\u2014";
            return Number(n).toLocaleString();
        }

        // ── Screened stock detail ──────────────────────────────

        async function fetchScreenedDetail(ticker) {
            contentEl.innerHTML = '<div class="loading"></div>';
            try {
                var res = await fetch("/screened/" + encodeURIComponent(ticker));
                if (!res.ok) throw new Error("Not found");
                var data = await res.json();
                renderScreenedDetail(data);
            } catch (err) {
                fetchLegacyDetail(ticker);
            }
        }

        function renderScreenedDetail(s) {
            var analysis = s.analysis || {};
            var html = "";

            // Header with DCF upside
            html += '<div class="detail-header">';
            html += '<div class="ticker">' + escapeHtml(s.ticker) + '</div>';
            html += '<span class="name">' + escapeHtml(s.short_name || "") + '</span>';
            if (s.market_cap) {
                html += '<span class="market-cap-label">' + formatMarketCap(s.market_cap) + '</span>';
            }
            html += '<span class="sector-label">' + escapeHtml(s.sector || "") + '</span>';
            if (s.industry && s.industry !== s.sector) {
                html += '<span class="sector-label">' + escapeHtml(s.industry) + '</span>';
            }
            if (s.dcf_upside_pct != null) {
                var upsideSign = s.dcf_upside_pct >= 0 ? "+" : "";
                html += '<div class="composite-score">';
                html += '<span class="composite-value">' + upsideSign + (s.dcf_upside_pct * 100).toFixed(0) + '%</span>';
                html += '<span class="composite-label">DCF Upside</span>';
                html += '</div>';
            }
            html += '</div>';

            // Why This Stock Was Selected
            var reasons = analysis.reasons || [];
            if (reasons.length > 0) {
                html += '<div class="explanation-section section-reasons">';
                html += '<div class="section-title">Why This Stock Was Selected</div>';
                html += '<ul>';
                for (var i = 0; i < reasons.length; i++) {
                    html += '<li>' + escapeHtml(reasons[i]) + '</li>';
                }
                html += '</ul></div>';
            }

            // DCF Valuation Detail
            if (analysis.intrinsic_value_per_share != null) {
                html += '<div class="explanation-section section-dcf">';
                html += '<div class="section-title">DCF Valuation</div>';
                html += '<div class="metric-grid">';
                html += metricRow("Intrinsic Value", "$" + analysis.intrinsic_value_per_share.toFixed(2));
                if (analysis.dcf_margin_of_safety != null)
                    html += metricRow("Margin of Safety", (analysis.dcf_margin_of_safety * 100).toFixed(1) + "%");
                if (analysis.dcf_upside_pct != null)
                    html += metricRow("Upside Potential", (analysis.dcf_upside_pct > 0 ? "+" : "") + (analysis.dcf_upside_pct * 100).toFixed(1) + "%");
                if (analysis.wacc != null)
                    html += metricRow("WACC", (analysis.wacc * 100).toFixed(1) + "%");
                if (analysis.fcf_yield != null)
                    html += metricRow("FCF Yield", (analysis.fcf_yield * 100).toFixed(1) + "%");
                if (analysis.ev_to_fcf != null)
                    html += metricRow("EV/FCF", analysis.ev_to_fcf.toFixed(1) + "x");
                html += '</div></div>';
            }

            // Key Metrics
            html += '<div class="explanation-section section-metrics">';
            html += '<div class="section-title">Key Metrics</div>';
            html += '<div class="metric-grid">';
            if (analysis.pe_ratio != null) html += metricRow("P/E Ratio", analysis.pe_ratio.toFixed(1));
            if (analysis.pb_ratio != null) html += metricRow("P/B Ratio", analysis.pb_ratio.toFixed(2));
            if (analysis.roe != null) html += metricRow("ROE", (analysis.roe * 100).toFixed(1) + "%");
            if (analysis.debt_to_equity != null) html += metricRow("D/E Ratio", analysis.debt_to_equity.toFixed(2));
            if (analysis.dividend_yield != null) html += metricRow("Div Yield", (analysis.dividend_yield * 100).toFixed(2) + "%");
            if (analysis.market_cap != null) html += metricRow("Market Cap", fmtMarketCap(analysis.market_cap));
            if (analysis.interest_coverage != null) html += metricRow("Interest Coverage", analysis.interest_coverage.toFixed(1) + "x");
            if (analysis.accruals_ratio != null) html += metricRow("Accruals Ratio", analysis.accruals_ratio.toFixed(3));
            html += '</div></div>';

            contentEl.innerHTML = html;
        }

        function metricRow(label, value) {
            return '<div class="metric-row"><span class="metric-label">' + label + '</span><span class="metric-value">' + escapeHtml(String(value)) + '</span></div>';
        }

        function fmtMarketCap(v) {
            if (v == null) return "\u2014";
            if (v >= 1e12) return "$" + (v / 1e12).toFixed(1) + "T";
            if (v >= 1e9) return "$" + (v / 1e9).toFixed(1) + "B";
            if (v >= 1e6) return "$" + (v / 1e6).toFixed(0) + "M";
            return "$" + v.toLocaleString();
        }

        // ── Legacy signal detail ───────────────────────────────

        async function fetchLegacyDetail(ticker) {
            contentEl.innerHTML = '<div class="loading"></div>';
            try {
                var res = await fetch("/signals/" + encodeURIComponent(ticker));
                if (!res.ok) throw new Error("Not found");
                var data = await res.json();
                renderLegacyDetail(data);
            } catch (err) {
                contentEl.innerHTML =
                    '<div class="empty-state"><div class="icon">&#9888;</div>' +
                    '<div class="title">Signal Not Found</div>' +
                    '<div class="subtitle">No data for ' + escapeHtml(ticker) + '.</div></div>';
            }
        }

        function renderLegacyDetail(s) {
            var conf = Math.round(s.confidence * 100);
            var html = "";

            html += '<div class="detail-header">';
            html += '<div class="ticker">' + escapeHtml(s.ticker) + '</div>';
            html += '<span class="name">' + escapeHtml(s.short_name || "") + '</span>';
            html += '<span class="sector-label">' + escapeHtml(s.sector || "") + '</span>';
            html += '<div class="confidence-bar">';
            html += '<span class="confidence-value">' + conf + '% confidence</span>';
            html += '</div></div>';

            if (s.ml_insight) {
                html += renderTextSection("Why This Stock", "ml", s.ml_insight);
            }
            if (s.fundamental && s.fundamental.points) {
                html += renderSection("Fundamentals", "fundamental", s.fundamental.points);
            }
            if (s.macro && s.macro.points) {
                html += renderSection("Industry & Macro Context", "macro", s.macro.points);
            }
            if (s.risk_context) {
                html += renderTextSection("Risk Considerations", "risk", s.risk_context);
            }
            if (s.historical_context) {
                html += renderTextSection("Historical Precedent", "history", s.historical_context);
            }

            contentEl.innerHTML = html;
        }

        function renderSection(title, cls, points) {
            var html = '<div class="explanation-section section-' + cls + '">';
            html += '<div class="section-title">' + title + '</div>';
            html += '<ul>';
            for (var i = 0; i < points.length; i++) {
                html += '<li>' + escapeHtml(points[i]) + '</li>';
            }
            html += '</ul></div>';
            return html;
        }

        function renderTextSection(title, cls, text) {
            return (
                '<div class="explanation-section section-' + cls + '">' +
                '<div class="section-title">' + title + '</div>' +
                '<p>' + escapeHtml(text) + '</p></div>'
            );
        }
    }

    // ── Explanation Panel ──────────────────────────────────────

    function initExplainPanel(contentEl) {
        var panel = document.getElementById("explain-panel");
        var termEl = document.getElementById("explain-term");
        var textEl = document.getElementById("explain-text");
        var whyEl = document.getElementById("explain-why");
        var closeBtn = document.getElementById("explain-close");
        if (!panel || !termEl || !textEl || !whyEl) return;

        var activeEl = null;

        contentEl.addEventListener("click", function (e) {
            var target = e.target.closest("[data-explain]");
            if (!target) return;
            var key = target.getAttribute("data-explain");
            var info = EXPLANATIONS[key];
            if (!info) return;

            if (activeEl) activeEl.classList.remove("active");
            target.classList.add("active");
            activeEl = target;

            termEl.textContent = info.title;
            textEl.textContent = info.text;
            whyEl.textContent = info.why;
            panel.classList.add("open");
        });

        closeBtn.addEventListener("click", function () {
            panel.classList.remove("open");
            if (activeEl) {
                activeEl.classList.remove("active");
                activeEl = null;
            }
        });
    }

    // ── Helpers ──────────────────────────────────────────────

    function formatMarketCap(cap) {
        if (cap == null) return "";
        if (cap >= 1e9) return "$" + (cap / 1e9).toFixed(1) + "B";
        if (cap >= 1e6) return "$" + (cap / 1e6).toFixed(0) + "M";
        return "";
    }

    function escapeHtml(str) {
        var div = document.createElement("div");
        div.appendChild(document.createTextNode(str));
        return div.innerHTML;
    }

})();
